# Generated by Django 2.2.7 on 2019-11-22 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='唯一id', max_length=255, unique=True)),
                ('bg_url', models.CharField(help_text='背景图片地址', max_length=255)),
                ('music_url', models.CharField(help_text='音乐地址', max_length=255, null=True)),
                ('image_urls', models.TextField(help_text='图片链接，用逗号分隔')),
                ('email', models.EmailField(help_text='通知邮箱', max_length=254, null=True)),
                ('createTime', models.DateTimeField(auto_now=True, help_text='时间')),
                ('user', models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.IntegerField(default=0, help_text='支付状态 0：未支付 1：已支付 2：审核中')),
                ('createTime', models.DateTimeField(auto_now=True, help_text='时间')),
                ('alum', models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to='user_manage.AlumModel')),
                ('user', models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
