# Generated by Django 2.2.7 on 2019-11-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(help_text='菜单名称', max_length=40, unique=True)),
                ('menu_path', models.CharField(help_text='菜单路径', max_length=40, unique=True)),
                ('remark', models.CharField(default=None, help_text='备注', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuManageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='菜单类型名称', max_length=40, unique=True)),
                ('remark', models.CharField(default=None, help_text='备注', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(help_text='菜单id', on_delete=django.db.models.deletion.CASCADE, to='menu_manage.MenuManage')),
            ],
        ),
    ]
