# Generated by Django 2.2.3 on 2019-09-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuManageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='菜单名称', max_length=20, unique=True)),
                ('remark', models.CharField(default=0, help_text='备注', max_length=120, null=True)),
            ],
        ),
    ]
