# Generated by Django 2.2.3 on 2019-09-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumanagetype',
            name='type_name',
            field=models.CharField(help_text='菜单类型名称', max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='MenuManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(help_text='菜单名称', max_length=40, unique=True)),
                ('menu_path', models.CharField(help_text='菜单路径', max_length=40, unique=True)),
                ('menu_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_manage.MenuManageType')),
            ],
        ),
    ]
